# Generated by Django 3.2.8 on 2022-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='num_product',
            field=models.IntegerField(default=None),
        ),
    ]
